import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

export const metadata = {
  title: "Globetrek",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', // فقط مسار من public/
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-white text-gray-900'>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
